[package]
name = "crateton"
version = "0.1.0"
authors = ["Will Crichton <wcrichto@cs.stanford.edu>"]
edition = "2018"
default-run = "crateton"

# [workspace]
# # members = ["crates/*"]
# exclude = ["scripts/example_script"]

[features]
default = ["bevy/default", "bevy/jpeg"]
web = ["bevy/png", "bevy/jpeg", "bevy/render", "bevy/bevy_winit", "bevy/bevy_gltf", "bevy_webgl2"]

[profile.release]
debug = true

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 2
debug = true
debug-assertions = true

[dependencies]
bevy = {version = "0.4.0", default-features = false}
bevy_rapier3d = "0.7.0"
ncollide3d = "0.26"
winit = {version = "0.24.0"}
#bevy_webgl2 = {version = "0.4.0", optional = true}
bevy_webgl2 = {git = "https://github.com/rparrett/bevy_webgl2", branch = "update-for-bevy-master", optional=true}
bevy_egui = "0.1.2"
bevy-inspector-egui = "0.3.0"
serde = {version = "1", features=["derive"]}
serde_json = "1"
anyhow = "1.0"
image = "0.23.12"
itertools = "0.10"
# bevy_skybox = "0.3.0"

# crateton_core = { path = "crates/crateton_core" }
# crateton_scripts = { path = "crates/crateton_scripts" }

[patch.crates-io]
bevy = { path = "../bevy" }
winit = { path = "../winit" }
bevy_winit = { path = "../bevy/crates/bevy_winit" } # only needed for bevy_egui
bevy_egui = { path = "../bevy_egui" }
bevy-inspector-egui = { path = "../bevy-inspector-egui" }
# bevy_skybox = { path = "../bevy_skybox" }