[package]
authors = ["Will Crichton <wcrichto@cs.stanford.edu>"]
default-run = "crateton"
edition = "2018"
name = "crateton"
version = "0.1.0"

[workspace]
members = ["crates/*"]

[features]
# default = [
#   "bevy/default",
#   "bevy/jpeg", # non-default bevy
#   "bevy/dynamic", # debug feature to improve compile times
#   "rustpython_features"
# ]

# web = [
#   "bevy/png", "bevy/render", "bevy/bevy_winit", "bevy/bevy_gltf",  # default bevy
#   "bevy/jpeg", # non-default bevy
#   "bevy_webgl2", "web-sys",
#   "rustpython_features"
# ]

# rustpython_features = ["rustpython-vm/freeze-stdlib", "rustpython-vm/compile-parse"]


[dependencies]
bevy = {version = "0.5.0", features = ["jpeg", "dynamic"]}

# Physics
bevy_rapier3d = {version = "0.10.2", features = ["simd-stable", "render"]}

# Ui
bevy-inspector-egui = {version = "0.6.1", features = ["rapier"]}
bevy_egui = "0.6.1"
syntect = {version = "4.5.0", default-features = false, features = ["default-fancy"]}

# Web
web-sys = {version = "0.3.46", optional = true}
# bevy_webgl2 = {git = "https://github.com/mrk-its/bevy_webgl2", optional = true}

# Scripts
rustpython-common = {git = "https://github.com/RustPython/RustPython"}
rustpython-vm = {git = "https://github.com/RustPython/RustPython", default-features = false, features = ["freeze-stdlib", "compile-parse"]}

# Misc
anyhow = "1.0"
itertools = "0.10"
serde = {version = "1", features = ["derive"]}
serde_json = "1"


###### Performance knobs

[profile.release]
debug = true

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
debug = true
debug-assertions = true
opt-level = 2
