[package]
name = "crateton"
version = "0.1.0"
authors = ["Will Crichton <wcrichto@cs.stanford.edu>"]
edition = "2018"

[workspace]
# members = ["crates/*"]
exclude = ["scripts/example_script"]

[profile.release]
debug = true

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = "0.4.0"
bevy_rapier3d = "0.7.0"
ncollide3d = "0.26"

# crateton_core = { path = "crates/crateton_core" }
# crateton_scripts = { path = "crates/crateton_scripts" }

[patch.crates-io]
bevy = { path = "../bevy" }
