on: push
name: Publish

jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: mkdir deps && cd deps && git clone https://github.com/willcrichton/bevy
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          target: wasm32-unknown-unknown
      - uses: davidB/rust-cargo-make@v1
      - run: cargo make build-web --profile release
      - run: cp -r assets wasm && rm -rf wasm/target
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./wasm
