on: push

name: Publish

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: wasm32-unknown-unknown
      - run: git clone https://github.com/bevyengine/bevy ../bevy && pushd ../bevy && git checkout 6a0116e994cb7d9d105cb0897f542701d955db88 && popd && git clone https://github.com/willcrichton/winit/ ../winit
      - run: cargo install cargo-make
      - run: cargo make build-web --profile release
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./wasm
