on: push
name: Publish

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: wasm32-unknown-unknown
      - run: pushd .. && git clone https://github.com/willcrichton/bevy && \
          git clone https://github.com/willcrichton/winit/ && \
          git clone https://github.com/willcrichton/bevy_egui/ && \
          git clone https://github.com/willcrichton/bevy-inspector-egui/ && popd
      - run: cargo install cargo-make
      - run: cargo make build-web --profile release
      - run: cp -r assets wasm
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./wasm
