[package]
name = "crateton_scripts"
version = "0.1.0"
authors = ["Will Crichton <wcrichto@cs.stanford.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustc_codegen_cranelift = { path = "../../../rustc_codegen_cranelift" }
cranelift-simplejit = { git = "https://github.com/bytecodealliance/wasmtime/", branch = "main" }
cranelift-module = { git = "https://github.com/bytecodealliance/wasmtime/", branch = "main" }
cranelift-codegen = { git = "https://github.com/bytecodealliance/wasmtime/", branch = "main" }
cranelift-frontend = { git = "https://github.com/bytecodealliance/wasmtime/", branch = "main" }